### ISSUE TITLE
Missing database name with CLICKHOUSE_DATABASE_SCHEME=http in CLICKHOUSE_URL

### ISSUE THREAD

**Issue by D1ceWard** [dokku/dokku-clickhouse#33]
## Description of problem

This is more of a question because I lack knowledge in the field, but for my use case I need database name in `CLICKHOUSE_URL`, so when linking a clickhouse database with an application that contains the environment variable `CLICKHOUSE_DATABASE_SCHEME=http` the link generated in `CLICKHOUSE_URL` does not contain the name of the database compared to the `clickhouse://` protocol.

### Steps to Reproduce

1. Create a dummy app `dokku create myapp`
2. Create a dummy clickhouse database `dokku clickhouse:create mydb`
3. Set CLICKHOUSE_DATABASE_SCHEME `dokku config:set myapp CLICKHOUSE_DATABASE_SCHEME=http`
4. Link database to the app `dokku clickhouse:link mydb myapp`
5. Print app config to get CLICKHOUSE_URL `dokku config myapp`

#### Actual Results

```
#> dokku config myapp
...
CLICKHOUSE_URL: http://mydb:password@dokku-clickhouse-mydb:8123/
...
```

#### Expected Results

```
#> dokku config myapp
...
CLICKHOUSE_URL: http://mydb:password@dokku-clickhouse-mydb:8123/mydb
...
```
Note the `mydb` at the end of the url.

**Comment by D1ceWard** [comment]
I see that in the PR #21 comments, it was for exactly the same use case with plausible asking for the database name in the url. So, nothing to do with `dokku-clickhouse` I'll ask the question on the Plausible side. Thanks for the details.

**Comment by gyfis** [comment]
Thanks @D1ceWard !
