### ISSUE TITLE
Predefine TTL for system log tables

### ISSUE THREAD

**Issue by nerg4l** [dokku/dokku-clickhouse#46]
## Description of problem

By default no TTL is defined for the following system log tables:

- asynchronous_metric_log
- metric_log
- part_log
- query_log
- query_thread_log
- query_views_log
- session_log
- trace_log

This can be problematic in the long term. I'm running a ClickHouse service since 2020 October which grow over 20 GiB on disk. I recently realized, most of the disk space is taken by system logs and not the table used by the application.

A predefined TTL could provide some safety for others using dokku-clickhouse as a service.

### Steps to Reproduce

1. Run ClickHouse for a long time.
2. Execute the query you can find below.

```sql
SELECT table,
       formatReadableSize(sum(bytes)) as size
FROM system.parts
WHERE active AND table LIKE '%_log'
GROUP BY table
ORDER BY table
```

#### Actual Results

| table | size |
| ----- | ---- |
| asynchronous_metric_log | 20.16 GiB |
| metric_log | 1.53 GiB |
| part_log | 105.47 MiB |
| query_log | 152.27 MiB |
| query_thread_log | 200.00 MiB |
| session_log | 172.86 KiB |
| trace_log | 3.57 GiB |

#### Expected Results

Lower storage footprint.

## Additional information

I added a `system_log_ttl_config.xml` to `config/config.d` with a 30 day TTL for logs. I'm monitoring the changes to see if this will keep the storage size low.

Content of `system_log_ttl_config.xml`:

```xml
<clickhouse>
    <part_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </part_log>
    <metric_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </metric_log>
    <trace_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </trace_log>
    <query_thread_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </query_thread_log>
    <query_views_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </query_views_log>
    <query_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </query_log>
    <session_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </session_log>
    <asynchronous_metric_log>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    </asynchronous_metric_log>
</clickhouse>
```

**Comment by josegonzalez** [comment]
Do you think those are reasonable defaults? I don't see why not, but I don't want to add them if there is something... negative about doing so...

**Comment by nerg4l** [comment]
I will monitor the service in the next couple of days to see how much the space growth, and tomorrow I can share more information about these logs.

**Comment by nerg4l** [comment]
I checked out all system logs and found I missed `query_views_log` because the service I work with does not use views (I updated the issue with that table). All these tables are for monitoring because they contain debug info or historical data about some kind of performance e.g. RAM usage, query execution time, login/logout success/failure. I think 30 days retention policy as default is reasonable and there is always an option to change it.

`asynchronous_metric_log`, `metric_log`, and `trace_log` seem to be the most problematic, especially `asynchronous_metric_log`. I truncated them about 12 hours ago and they are already in megabytes. I expect `asynchronous_metric_log` to reach 800 MiB in 30 days.

| table | size |
| --- | --- |
| asynchronous_metric_log | 53.21 MiB |
| metric_log | 3.74 MiB |
| part_log | 143.21 KiB |
| query_log | 349.27 KiB |
| query_thread_log | 574.35 KiB |
| session_log | 26.29 KiB |
| trace_log | 9.44 MiB |

---

Description of each table and some additional information when needed:

[`asynchronous_metric_log`](https://clickhouse.com/docs/en/operations/system-tables/asynchronous_metric_log)

> Contains the historical values for system.asynchronous_metrics, which are saved once per minute. Enabled by default.

`asynchronous_metrics`

> Contains metrics that are calculated periodically in the background. For example, the amount of RAM in use.

[`metric_log`](https://clickhouse.com/docs/en/operations/system-tables/metric_log)

> Contains history of metrics values from tables system.metrics and system.events, periodically flushed to disk.

`metrics`

> Contains metrics which can be calculated instantly, or have a current value. For example, the number of simultaneously processed queries or the current replica delay. This table is always up to date.

`events`

> Contains information about the number of events that have occurred in the system. For example, in the table, you can find how many `SELECT` queries were processed since the ClickHouse server started.

[`part_log`](https://clickhouse.com/docs/en/operations/system-tables/part_log)

> This table contains information about events that occurred with [data parts](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/custom-partitioning-key) in the [MergeTree](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree) family tables, such as adding or merging data.

[`query_log`](https://clickhouse.com/docs/en/operations/system-tables/query_log)

> Contains information about executed queries, for example, start time, duration of processing, error messages.

[`query_thread_log`](https://clickhouse.com/docs/en/operations/system-tables/query_thread_log)

> Contains information about threads that execute queries, for example, thread name, thread start time, duration of query processing.

[`query_views_log`](https://clickhouse.com/docs/en/operations/system-tables/query_views_log)

> Contains information about the dependent views executed when running a query, for example, the view type or the execution time.

[`session_log`](https://clickhouse.com/docs/en/operations/system-tables/session_log)

> Contains information about all successful and failed login and logout events.

[`trace_log`](https://clickhouse.com/docs/en/operations/system-tables/trace_log)

> Contains stack traces collected by the sampling query profiler.

**Comment by nerg4l** [comment]
After 30 days the tables reached ~3.5 GB. It is definitely friendlier than the previous indefinite size.

| table | size |
| --- | --- |
| asynchronous_metric_log | 2.82 GiB |
| metric_log | 205.69 MiB |
| part_log | 11.10 MiB |
| query_log | 15.92 MiB |
| query_thread_log | 22.55 MiB |
| session_log | 25.97 KiB |
| trace_log | 512.03 MiB |

According to https://clickhouse.com/docs/en/operations/monitoring/ these tables are to provide metrics for [Graphite](https://github.com/graphite-project) and [Prometheus](https://prometheus.io/).
